from enum import Enum

class IntentLabel(str, Enum):
    GREETING = "GREETING"
    RAG_QUERY = "RAG_QUERY"
    CODE_GEN = "CODE_GEN"
    GENERAL_CHAT = "GENERAL_CHAT"
    WEB_SEARCH = "WEB_SEARCH"
    TASK_PLANNING = "TASK_PLANNING"
    FILE_OPERATIONS = "FILE_OPERATIONS"
    CAPABILITY = "CAPABILITY"
