"""
Global Agent State definition for the LangGraph orchestrator.
"""
from typing import Annotated, TypedDict, List, Dict, Any
from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages

class AgentState(TypedDict):
    # add_messages appends new conversation turns automatically to the list
    messages: Annotated[List[AnyMessage], add_messages]
    
    # Mission Plan (To-Do List generated by the LangGraph planner logic)
    plan: List[str]
    
    # Relational Context retrieved via Phase 1 SQL-RAG architecture
    relational_context: Dict[str, Any]
    
    # For error tracking and self-healing conditions
    last_action_status: str  # "success", "error", or "pending"
    
    # Role-Based Access Control logic (Phase 6 Keycloak integration)
    user_roles: List[str]  # Added for Keycloak RBAC
    user_id: str           # For audit trails

